config/routes.rb
Rails.application.routes.draw do
  resources :chart
  resources :categories
  resources :states
  resources :jobs do
    collection do
      get :create_new_job
    end
    member do
      get :search
      get :search_by_category
      get :search_by_state
    end
  end

  resources :hires do
    collection do
      get :new_invitation
    end
    member do
      get :invitation
      get :hire
      get :suspend
    end
  end

  resources :chats do
    collection do
      get :kick_out
      get :msg
      get :filter_by_user
      get :bid_by_user
      get :check_kicked
    end
  end

  resources :rooms do
    collection do
      post :msg
    end
    member do
      get :enterRoom
      get :search_by_category
    end
  end 
  resources :users do
    collection do
      post :login
      get :management
      get :exchange_used
    end
  end
  root 'jobs#index'

end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: true
    validates :password, confirmation: true

    has_many    :chats
    has_many    :rooms
    has_many    :jobs
    has_many    :hires

    accepts_nested_attributes_for :chats, :allow_destroy => true
    accepts_nested_attributes_for :rooms, :allow_destroy => true
    accepts_nested_attributes_for :jobs, :allow_destroy => true
    accepts_nested_attributes_for :hires, :allow_destroy => true

    def self.authenticate(username, password)
        user = User.find_by_name(username)
        if user.blank? || 
            Digest::SHA256.hexdigest(password + user.salt) != user.password
            nil
        else
            user
        end
    end

    def self.identify_user(username)
        user = User.find_by_name(username)
        if user.blank?
            "true"
        else
            "false"
        end
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    session[:user] = nil
    redirect_to '/jobs'
    # @users = User.all

  end


  # GET /users/1
  def show
    @job_per_user = Job.where(:user_id => params[:id])
    @hire_per_user = Hire.where(:user_id => params[:id])

    @edit_button_show = 0
    if session[:user]['id'].to_s == params[:id]
      @edit_button_show = 1
    end
  end

  # GET /users/new
  def new
    @user = User.new
    @user.password = ''
  end

  def login
    logUser = user_params
    @user = User.authenticate(logUser[:name], logUser[:password])
    if @user
      session[:user] = @user
      redirect_to '/jobs'
    else
      @notice = 'Login Failed'
      index
    end
  end
  
  # GET /users/1/edit
  def edit
  end

  def update_user_params
    new_user = user_params
    (user_params['image_url'] == nil)? new_user['image_url'] = 'anonymous.png': new_user['image_url'] = user_params['image_url'].original_filename
    new_user[:salt] = [Array.new(6){rand(256).chr}.join].pack('m').chomp
    new_user[:password] = Digest::SHA256.hexdigest(user_params[:password] + new_user[:salt])
    new_user[:password_confirmation] = Digest::SHA256.hexdigest(user_params[:password_confirmation] + new_user[:salt])

    new_user
  end

  # POST /users
  def create

    nuser = update_user_params()
    nuser[:address] = request.remote_ip
    exist = User.identify_user(nuser[:name])
    @user = User.new(nuser)
    if exist == 'true'
      if @user.save
        upload_image(params[:user])
        redirect_to '/users'
      else
        @notice = 'Sorry, Sign up failed'
        render(:template => 'users/new')
      end  
    else
      @notice = nuser[:name]+' already exists'
      render(:template => 'users/new')
    end
 
  end

  # PATCH/PUT /users/1
  def update
    nuser = update_user_params()
    if @user.update(nuser)
      session[:user] = @user
      upload_image(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def upload_image(upload)
    if upload['image_url'] != nil
      name = upload['image_url'].original_filename
      directory = 'app/assets/images/users'
      path = File.join(directory, name)
      File.open(path, 'wb') { |f| f.write(upload['image_url'].read) }
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def management
    @users = User.all
    render :_management
  end

  def exchange_used

    user_id = ajax_exchange_used_params[:user_id]
    @user = User.find(user_id)
    update_state = @user[:used] == 1 ? 0 : 1
    @user.update_attribute(:used, update_state)

    render text:'success'
  end

  # def address_update
    
  #   user_name = params[:send_data]['user_name']
  #   @user = User.where(:name => user_name.to_s)
  #   address = params[:send_data]['remoteAddress']
  #   if @user != nil
  #     @user.update_all('address = ' + address.to_s)
  #   end
  #   render text:'success'
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :salt, :image_url, :location, :role, :skill)
    end

    def ajax_exchange_used_params
      params.require(:send_data).permit(:user_id)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <label><%= f.label :name %></label>
  <%= f.text_field :name, class:'form-control' %>
</div>
<br>
  <div class="form-group">
    <label><%= f.label :skill %></label>
    <%= f.text_field :skill, class:'form-control' %>
  </div>
  <br>
<div class="form-group">
  <label><%= f.label :password %></label>
  <%= f.password_field :password, class:'form-control' %>
</div>
<br>
<div class="form-group">
  <label><%= f.label :password_confirmation %></label>
  <%= f.password_field :password_confirmation, class:'form-control' %>
</div>
<br>
<div class="form-group">
  <div>
    <%= f.label :image_url %>
  </div>
  <div style="color:white">
    <%= f.file_field :image_url, class:'form-control' %>
  </div>
</div>
<br>
<div class="form-group">
  <%= f.submit :update, class:'btn btn-primary btn-lg mb-xlg' %>
</div>
<% end %>

app/views/users/_management.html.erb
<div class="row">
  <div class="col-md-12">
    <h4>Users</h4>
    <table class="table">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Role</th>
        <th>Skill</th>
        <th>Used</th>
        <th>SignUp Date</th>
        <th>Address</th>
      </tr>
      </thead>
      <tbody>
      <%	 index = 0 %>
      <%	 @users.each do |user| %>
      <tr>
        <th scope="row">
          <%=	 index = index + 1 %>
        </th>
        <td>
          <%=	 user.name %>
        </td>
        <td>
          <%=	 user.role %>
        </td>
        <td>
          <%=	 user.skill %>
        </td>
        <td>
          <select class="user_used" id="<%=	user.id %>">
            <option <%	if user.used == 1 %> selected <% end %>>true</option>
            <option <%	if user.used == 0 %> selected <% end %>>false</option>
          </select>
        </td>
        <td>
          <%=	 user.created_at %>
        </td>
        <td>
          <%=	 user.address %>
        </td>
      </tr>
      <%	 end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/client-profile.erb
<h3>Job History</h3>

<% if @job_per_user.length > 0 %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Date</th>
        <th>Category</th>
      </tr>
      </thead>
      <tbody>
      <% @job_per_user.each do |job| %>
          <tr>
            <td>
          <%	 if job.state_id == 1 %>
                  <i class="fa fa-paper-plane" data-plugin-tooltip data-original-title="New"></i>
          <%	 elsif job.state_id == 2 %>
                  <i class="fa fa-check" data-plugin-tooltip data-original-title="Finish"></i>
          <%	 elsif job.state_id == 3 %>
                  <i class="fa fa-history" data-plugin-tooltip data-original-title="Hired"></i>
          <%	 elsif job.state_id == 4 %>
                  <i class="fa fa-exclamation" data-plugin-tooltip data-original-title="Suspend"></i>
          <% end %>
            </td>
            <td><%= job.title %></td>
            <td><%= job.description %></td>
            <td><%= job.reg_date.to_datetime.strftime('%Y-%m-%d %H:%M') %></td>
            <td><%= job.category.category_name %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <h4>No Hires</h4>
<% end %>

app/views/users/edit.html.erb
<%=	 render :file => 'users/page-header' %>
<h1 style="padding-left:120px;">Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/freelancer-profile.erb
<h3>Hire History</h3>

<% if @hire_per_user.length > 0 %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>State</th>
        <th>Related job</th>
        <th>Date</th>
        <th>Client</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>
          <% @hire_per_user.each do |hire| %>
              <% if hire.state_id == 1 %>
                  <i class="fa fa-paper-plane" data-plugin-tooltip data-original-title="New"></i>
              <% elsif hire.state_id == 2 %>
                  <i class="fa fa-check" data-plugin-tooltip data-original-title="Finish"></i>
              <% elsif hire.state_id == 3 %>
                  <i class="fa fa-history" data-plugin-tooltip data-original-title="Hired"></i>
              <% elsif hire.state_id == 4 %>
                  <i class="fa fa-exclamation" data-plugin-tooltip data-original-title="Suspend"></i>
              <% elsif hire.state_id == 5 %>
                  <i class="fa fa-exclamation" data-plugin-tooltip data-original-title="Invitation"></i>
              <% end %>
              </td>
              <td><%= hire.job.title %></td>
              <td><%= hire.job.reg_date.to_datetime.strftime('%Y-%m-%d %H:%M') %></td>
              <td><%= hire.job.user.name %></td>
              </tr>
          <% end %>
          </tbody>
    </table>
<% else %>
    <h4>No Hires</h4>
<% end %>

app/views/users/index.html.erb
<div class="login-div">
  <div>
    <label class="login-label">UserName</label>
    <input name="username" type="text" placeholder="UserName...">
  </div>
  <div>
    <label class="login-label">Password</label>
    <input name="password" type="password" placeholder="Password...">
  </div>
  <div>
      <a href="/" style="padding-left:10px; ">Back</a>
      <button class="user_select_submit" style="margin-left:45% ; margin-bottom:10px;" >Login</button>
  </div>
</div>
<div class="table-div">
  <table>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <a>
            <img src='<%= "/assets/users/anonymous.png" %>' class="avatar-80" />
          </a>
        </td>
        <td class="username" style="padding-left:15px"><p class="table-p"><%= user.name %></p></td>
        <% if session[:user] && session[:user]['role'] != 'user' %>
          <td style="padding-left:15px"><%= link_to 'Edit', edit_user_path(user) %></td>
          <td style="padding-left:15px"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<form method="POST" action="/users" enctype="multipart/form-data">
    <input name="authenticity_token" type="hidden">
    <div class="field">
        <label>Name</label>
        <input name="user[name]" type="text" id="username" value="<%= @user.name %>">
    </div>
    <br>
    <div class="field">
        <label>Password</label>
        <input name="user[password]" type="password" id="userpassword" value="<%= @user.password %>">
    </div>
    <br>
    <div class="field">
        <label>Confirm password</label>
        <input id="passwordconfirm" type="password" value="<%= @user.password %>">
    </div>
    <br>
    <div class="field">
      <select>
        <option>client</option>
        <option>freelancer</option>
      </select>
    </div>
    <br>
    <div class="field">
        <div style="color:white">
            Image_url
          </div>
        <div style="color:white">
            <input type="file" name="user[image_url]" id="userimage_url">
          </div>
      </div>

  <br>
    <div class="actions" style="cursor: pointer; margin-bottom:20px;">
        <a id="signup">Sign up</a>
    </div>

    <p style=" color: red; font-size: 32px;"><%=@notice%></p>
</form>

<%= link_to 'Back', users_path %>

app/views/users/page-header.erb
<section class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><%=	 link_to 'Home', jobs_path %></li>
          <li class="active">Profile</li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%=	 render :file => 'users/page-header' %>
<div class="container">
  <div class="row">
    <div class="col-md-1">
      <div >
        <img style="height: 80px; width: 80px;" src='<%= '/assets/users/'+@user.image_url %>' />
      </div>
    </div>
    <div class="col-md-11">

      <h2 class="mb-none"><strong><%= @user.name %></strong></h2>
      <h4 class="heading-primary"><%= @user.location %></h4>
      <% if @edit_button_show == 1 %>
          <%= link_to 'Edit', edit_user_path(@user) %>
      <% end %>
      <hr class="solid">
      <h3>Skills</h3>
      <%	 @user.skill.split(' ').each do |skill| %>
          <span class="label label-lg label-warning"><%= skill %></span>
      <%	 end %>

      <hr class="solid">
      <%	 if session[:user]['role'] == 'client' %>
          <%=	 render :file => 'users/client-profile' %>
      <%	 elsif session[:user]['role'] == 'freelancer' %>
          <%=	 render :file => 'users/freelancer-profile' %>
      <%	 end %>

    </div>
  </div>

</div>