config/routes.rb
Rails.application.routes.draw do
  resources :chart
  resources :categories
  resources :states
  resources :jobs do
    collection do
      get :create_new_job
    end
    member do
      get :search
      get :search_by_category
      get :search_by_state
    end
  end

  resources :hires do
    collection do
      get :new_invitation
    end
    member do
      get :invitation
      get :hire
      get :suspend
    end
  end

  resources :chats do
    collection do
      get :kick_out
      get :msg
      get :filter_by_user
      get :bid_by_user
      get :check_kicked
    end
  end

  resources :rooms do
    collection do
      post :msg
    end
    member do
      get :enterRoom
      get :search_by_category
    end
  end 
  resources :users do
    collection do
      post :login
      get :management
      get :exchange_used
    end
  end
  root 'jobs#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <!-- Basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Upwork in Unit 2</title>
  <%= csrf_meta_tags %>

  <meta name="keywords" content="HTML5 Template"/>
  <meta name="description" content="Porto - Responsive HTML5 Template">
  <meta name="author" content="okler.net">


</head>
<body>
  <div class="body">
    <%= render :file => 'layouts/header' %>

    <div role="main" class="main">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/header.erb
<%= render :file => 'layouts/import-css' %>
<header id="header" class="narrow" style="min-height:45px;" data-plugin-options='{"alwaysStickyEnabled": true, "stickyEnabled": true, "stickyWithGap": false, "stickyChangeLogoSize": false}'>
<div class="container" style="height:45px;">
  <div class="logo" style="padding:0px 0px 8px 0px;">
    <a href="/">
      <img alt="Porto" width="111" height="54" data-sticky-width="82" data-sticky-height="40" src="/assets/upworkLogo.png">
    </a>
  </div>
</div>

<div class="navbar-collapse nav-main-collapse collapse">
  <div class="container">
    <nav class="nav-main mega-menu">
      <ul class="nav nav-pills nav-main" id="mainMenu" >
        <% if session[:user] %>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#">
                Job
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Job list', jobs_path %></li>
                <% if session[:user]['role'] == 'client' %>
                    <li><%= link_to 'New job', new_job_path %></li>
                <% end %>
              </ul>
            </li>
        <% end %>


        <% if session[:user] %>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" id="contract-menu">
                Contract
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Contract list', '/rooms' %></li>
              </ul>
            </li>
            <li class="dropdown">
              <%= link_to 'Statistic', '/chart/index' %>
            </li>
            <% if session[:user]['name'] == 'admin' %>
                <li class="dropdown">
                  <%= link_to 'Users', '/users/management' %>
                </li>
            <% end %>
            <% if session[:user]['role'] == 'client' %>
                <li class="dropdown">
                  <%= link_to 'Categories', '/categories' %>
                </li>
            <% end %>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#">
                <%= session[:user]['name'] %>(<%= session[:user]['role'] %>)
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', user_path(session[:user]['id']) %></li>
                <li><%= link_to 'Log out', users_path %></li>
              </ul>
            </li>
        <% end %>

        <% if not session[:user] %>
            <li class="dropdown mega-menu-item mega-menu-signin signin" id="headerAccount">
              <a class="dropdown-toggle" href="#">
                <i class="fa fa-user"></i> Sign In
              </a>
              <ul class="dropdown-menu">
                <li>
                  <div class="mega-menu-content">
                    <div class="row">
                      <div class="col-md-12">
                        <%= render :file => 'layouts/signin-form' %>
                        <%= render :file => 'layouts/signup-form' %>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>
</header>
<%= render :file => 'layouts/import-js' %>

app/views/layouts/import-css.erb
<!-- Favicon -->
<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Web Fonts  -->
<!--<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">-->

<!-- Vendor CSS -->
<link rel="stylesheet" href="/assets/css/vendor/bootstrap/bootstrap.css">
<link rel="stylesheet" href="/assets/css/vendor/fontawesome/css/font-awesome.css">
<link rel="stylesheet" href="/assets/css/vendor/fontawesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/assets/css/vendor/owlcarousel/owl.carousel.min.css" media="screen">
<link rel="stylesheet" href="/assets/css/vendor/owlcarousel/owl.theme.default.min.css" media="screen">
<link rel="stylesheet" href="/assets/css/vendor/magnific-popup/magnific-popup.css" media="screen">

<!-- Theme CSS -->
<link rel="stylesheet" href="/assets/css/theme.css">
<link rel="stylesheet" href="/assets/css/theme-elements.css">
<link rel="stylesheet" href="/assets/css/theme-blog.css">
<link rel="stylesheet" href="/assets/css/theme-shop.css">
<link rel="stylesheet" href="/assets/css/theme-animate.css">

<!-- Current Page CSS -->
<link rel="stylesheet" href="/assets/css/vendor/rs-plugin/css/settings.css" media="screen">
<link rel="stylesheet" href="/assets/css/vendor/circle-flip-slideshow/css/component.css" media="screen">

<!-- Skin CSS -->
<link rel="stylesheet" href="/assets/css/skins/default.css">

<!-- Theme Custom CSS -->
<link rel="stylesheet" href="/assets/css/custom.css">
<!---->
<!-- Head Libs -->
<script src="/assets/css/vendor/modernizr/modernizr.js"></script>

app/views/layouts/import-js.erb
<!-- Vendor -->
<!--[if gte IE 9]><!-->
<script src="/assets/css/vendor/jquery/jquery.js"></script>

<!--<![endif]-->
<script src="/assets/css/vendor/jquery.appear/jquery.appear.js"></script>
<script src="/assets/css/vendor/jquery.easing/jquery.easing.js"></script>
<script src="/assets/css/vendor/jquery-cookie/jquery-cookie.js"></script>
<script src="/assets/css/vendor/bootstrap/bootstrap.js"></script>
<script src="/assets/css/vendor/common/common.js"></script>
<script src="/assets/css/vendor/jquery.validation/jquery.validation.js"></script>
<script src="/assets/css/vendor/jquery.stellar/jquery.stellar.js"></script>
<script src="/assets/css/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js"></script>
<script src="/assets/css/vendor/jquery.gmap/jquery.gmap.js"></script>
<script src="/assets/css/vendor/isotope/jquery.isotope.js"></script>
<script src="/assets/css/vendor/owlcarousel/owl.carousel.js"></script>
<script src="/assets/css/vendor/jflickrfeed/jflickrfeed.js"></script>
<script src="/assets/css/vendor/magnific-popup/jquery.magnific-popup.js"></script>
<script src="/assets/css/vendor/vide/vide.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="/assets/js/theme.js"></script>

<!-- Specific Page Vendor and Views -->
<script src="/assets/css/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
<script src="/assets/css/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<script src="/assets/css/vendor/circle-flip-slideshow/js/jquery.flipshow.js"></script>
<script src="/assets/js/views/view.home.js"></script>
<script src="/assets/js/jquery-bootpag/jquery.bootpag.min.js"></script>

<!-- Theme Custom -->
<script src="/assets/js/custom.js"></script>
<!-- Theme Initialization Files -->
<script src="/assets/js/theme.init.js"></script>
<!-- Theme Initialization Files -->
<script src="/assets/socket.io.js"></script>

<script src="/assets/users.js"></script>
<script src="/assets/hires.js"></script>
<script src="/assets/jobs.js"></script>
<!--<script src="/assets/rails.js"></script>-->

app/views/layouts/search-form.erb
<div class="input-group input-group-lg">
  <input type="text" class="form-control" placeholder="Search..." id="search-field">
</div>

app/views/layouts/sidebar.erb
<div class="col-md-3">
  <aside class="sidebar">

    <%=	 render :file=>'layouts/search-form' %>

    <hr>

    <h4 class="heading-primary">Categories</h4>

    <ul class="nav nav-list mb-xlg">
        <li ><a onclick="find_by_category(0)" class="side_bar_category" id="cate_0" href="#">All</a></li>
      <%	 @categories.each do |category| %>
          <li ><a onclick="find_by_category(<%= category.id %>)" class="side_bar_category" id=cate_<%= category.id %> href="#"><%=	 category.category_name %></a></li>
      <%	 end %>
    </ul>

    <hr>

    <h4 class="heading-primary">States</h4>

    <ul class="nav nav-list mb-xlg">
      <li><a onclick="find_by_state(0)" class="side_bar_state" id="state_0" href="#">All</a></li>
      <%	 @states.each do |state| %>
          <li><a onclick="find_by_state(<%= state.id %>)" class="side_bar_state" id=state_<%= state.id %> href="#"><%=	 state.state_name %></a></li>
      <%	 end %>
    </ul>

  </aside>
</div>

app/views/layouts/signin-form.erb
<div class="signin-form">

  <span class="mega-menu-sub-title">Sign In</span>

  <form id="frmSignIn" class="login-div" method="POST" action="/users/login" enctype="multipart/form-data">
    <input name="authenticity_token" type="hidden">
    <div class="row">
      <div class="form-group">
        <div class="col-md-12">
          <label>Username or E-mail Address</label>
          <input name="user[name]" type="text" value="" class="form-control input-lg" tabindex="1">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-group">
        <div class="col-md-12">
          <label>Password</label>
          <input name="user[password]" type="password" value="" class="form-control input-lg" tabindex="2">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <!--<span class="remember-box checkbox">-->
        <!--<label for="rememberme">-->
        <!--<input type="checkbox" id="rememberme" name="rememberme">Remember Me-->
        <!--</label>-->
        <!--</span>-->
      </div>
      <div class="col-md-6">
        <input id="signin" type="submit" value="Login" class="btn btn-primary pull-right mb-xl" data-loading-text="Loading...">
      </div>
    </div>
  </form>

  <p class="sign-up-info">Don't have an account yet? <a href="#" id="headerSignUp">Sign Up</a></p>

</div>

app/views/layouts/signup-form.erb
<div class="signup-form">
  <span class="mega-menu-sub-title">Create Account</span>

  <form method="POST" action="/users" id="frmSignUp" enctype="multipart/form-data">
    <input name="authenticity_token" type="hidden">
    <div class="row">
      <div class="form-group">
        <div class="col-md-12">
          <label>Name</label>
          <input name="user[name]" id="username" type="text" value="" class="form-control input-md">
        </div>
      </div>
    </div>
    <!--<div class="row">-->
      <!--<div class="form-group">-->
        <!--<div class="col-md-12">-->
          <!--<label>User detail</label>-->
          <!--<input name="user[location]" id="userloc" type="text" value="" class="form-control input-md">-->
        <!--</div>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="row">-->
      <!--<div class="form-group">-->
        <!--<div class="col-md-12">-->
          <!--<label>Skill</label>-->
          <!--<input name="user[skill]" id="userskill" type="text" value="" class="form-control input-md">-->
        <!--</div>-->
      <!--</div>-->
    <!--</div>-->
    <div class="row">
      <div class="form-group">
        <div class="col-md-12">
          <label>Role</label>
          <select name="user[role]" class="form-control mb-md">
            <option value="client">client</option>
            <option value="freelancer">freelancer</option>
          </select>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-group">
        <div class="col-md-12">
          <label>Your image!</label>
          <input type="file" class="form-control input-md" name="user[image_url]" id="userimage_url">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-group">
        <div class="col-md-6">
          <label>Password</label>
          <input name="user[password]" id="userpassword" type="password" value="" class="form-control input-md">
        </div>
        <div class="col-md-6">
          <label>Re-enter Password</label>
          <input name="user[password_confirmation]" id="confirmpassword" type="password" value="" class="form-control input-md">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <input id="signup" type="submit" value="Create Account" class="btn btn-primary pull-right mb-xl">
      </div>
    </div>
  </form>

  <p class="log-in-info">Already have an account? <a href="#" id="headerSignIn">Log In</a></p>
</div>